[project]
name = "guardai-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "dashscope>=1.20.11",
    "fastapi>=0.115.0",
    "lap>=0.5.12",
    "numpy>=1.26.4",
    "opencv-python>=4.10.0",
    "pydantic>=2.9.2",
    "python-dotenv>=1.0.1",
    "python-multipart>=0.0.9",
    "ultralytics>=8.3.0",
    "uvicorn[standard]>=0.30.6",
]
